[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Cache-Control = "max-age=31536000"
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"